.ig
..
.TH dood 1 "Nov 2019" "doo 0.1" "dood - a docker on overdrive cli tool"

.SH NAME
dood - docker on overdrive

.SH SYNOPSIS
dood [options]

.SH DESCRIPTION
dood is a docker cli tool to simplify containers administration.

.SH COMMANDS
.TP
.B "commands not listed below e.g : ""dood sh"" ""dood bash"" ""dood mycommand""
docker exec -it container_id arguments
.TP
.B "logs"
docker logs
.TP
.B "top"
docker top
.TP
.B "stats"
docker stats
.TP
.B "inspect"
docker inspect
.TP
.B "stop"
docker stop
.TP
.B "restart"
docker restart
.TP
.B "kill"
docker kill
.TP
.B "rm"
docker rm
.TP
.B "wait"
docker wait
.TP
.B "pause"
docker pause
.TP
.B "unpause"
docker unpause

.SH LICENSE
MIT
